- hosts: localhost
  connection: local
  tasks:
  - name: create container
    docker_container:
      name: myweb
      image: "sjleenobreak/hello-world:{{ lookup('env','BUILD_NUMBER') }}""
      state: started
      ports:
        - 80:8080
